# Generated by Django 2.0.4 on 2018-04-28 07:31

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ajaximage.fields.AjaxImageField()),
                ('thumbnail', ajaximage.fields.AjaxImageField()),
            ],
        ),
    ]
